# Register
POST http://localhost:5555/register
content-type: application/json

{
  "name": "Anisphia",
  "email": "anisphia@gmail.com"
}

###

# Login
POST http://localhost:5555/login
Content-Type: application/json

{
  "email": "anisphia@gmail.com"
}

###